### ISSUE TITLE
遇到一些问题

### ISSUE THREAD

**Issue by beckbikang** [danloh/toplog#2]
error[E0658]: use of unstable library feature 'inner_deref': newly added
   --> /Users/macy/.cargo/registry/src/github.com-1ecc6299db9ec823/lettre-0.9.3/src/smtp/commands.rs:248:61
    |
248 |             Some(mechanism.response(&credentials, challenge.as_deref())?)
    |                                                             ^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/50264

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.

**Comment by danloh** [comment]
what's your rustc version?  it is OK here on 1.46
